### PR TITLE
If no division option is given to the script then it will query to fi…

### PR DESCRIPTION
**Pull request by ens-st3**
…nd all and then run against each. If division is specified then the output is the same as before this commit

I don't expect you to accept this but it demonstrates how we'd like to use this, ie to be able to run it once over all divisions when you hand over to us.

The other thing that we'd like to be able to do is to have the output to SDTOUT rather than files, but that's more involved when it comes to running against all divisions

### CODE REVIEW

**Comment by ens-st3** [comment]
Glad you like the idea. We could work with either named files or named directories, but if this were a wish list we'd ask for a single file (or screen output) summarising everything across all divisions (see below for a rough idea). I don't know how this fits in with your use of this for the FTP site though.

------------------------
New genomes
- division 1
--species 1 name etc
--species 2 name etc
- division 2
-- species name etc
- division 3 etc

Updated assemblies
- division 1 etc

Updated annotations etc

**Comment by james-monkeyshines** [comment]
Regarding having a single set of output sent to screen, I think that'd need lots of logic in the script to make it that customisable. But we don't need to have a single script that works for all use cases. What about a new script, "summary_genomes.pl", say, which uses almost identical API calls to output in the desired format?

**Comment by ens-st3** [comment]
That would work for us

**Comment by thomasmaurel** [comment]
@james-monkeyshines and @ens-st3: I will create a JIRA ticket for creating this new  "summary_genomes.pl" script.

**Comment by thomasmaurel** [comment]
I will create a new script matching Steve requirement, see here for details: https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-3032

**Pull request closed without merging**
